### ISSUE TITLE
v0.0.2 - Auth and Hosting

### ISSUE THREAD

**Issue by popcorn245** [MadnessLabs/MadnessLabs2019#3]
### Get auth buttons on the home page that login with the following providers:
- [x] Github
- [x] Facebook
- [x] Twitter
- [x] Google

### Helpful Links:
Firebase Auth Docs - https://firebase.google.com/docs/auth
Madness Labs Project Auth Tab - https://console.firebase.google.com/u/0/project/madness-labs/authentication

### Successful When:
All login methods should be tested and there should be one of each account in the Auth Tab on Firebase console.

## 2 ) Get the site hosted online

Use the firebase cli to deploy the site to the intertubes.

### Helpful Links:
Madness Labs Firebase Hosting - https://madness-labs.web.app/
Firebase Hosting Docs: https://firebase.google.com/docs/hosting/quickstart?authuser=0

### Successful When:
We can see the project at the hosting link above and can login with all the methods online.

**Comment by aaronmhappe** [comment]
ml-3-2

**Comment by meaustin15** [comment]
Auth setup and site hosting complete
