### ISSUE TITLE
v0.0.2 - Home Page

### ISSUE THREAD

**Issue by Giggles0369** [MadnessLabs/MadnessLabs2019#5]
# RESOURCES

### MadnessLabs-Templates-Home:
XD Review: https://xd.adobe.com/view/78799670-cfd3-45c9-5542-6d17ea457b30-0e48/?fullscreen
XD Development: https://xd.adobe.com/spec/c0226d32-cbe0-40a0-6b52-3d3784776f27-b613/

### MadnessLabs-StyleGuide:
XD Development: https://xd.adobe.com/spec/ab7d9563-1c88-4879-72e4-af51993e1c40-dd4c/

# WHAT

Create the new ML home page!

# REQUIREMENTS

- [ ] logo
- [ ] video
- [ ] animations
- [ ] Get latest blog post with Fetch API

# NOTES
Link to the JSON data for latest blog post:
https://madnesslabs.net/api/v1/feed

Link to JavaScript Fetch API Docs:
https://developers.google.com/web/updates/2015/03/introduction-to-fetch

Remember to do this inside of the home page component.

**Comment by popcorn245** [comment]
Here is a helpful page for working with video elements. You will need to put both .mov and .mp4 as sources. The video assets are in the /src/assets/videos directory.
https://www.w3schools.com/html/html5_video.asp

**Comment by sphynx245** [comment]
that styleguide will be updated over time. ignore the RAF stuff in there please
